### ISSUE TITLE
Create contributing guide

### ISSUE THREAD

**Issue by quanghung97** [sun-asterisk-research/multi-select-areas-image#1]
Create a simple contributing guide, which covers:

- how/when to open an issue
- how to contribute with code

**Comment by pniedzwiedzinski** [comment]
I would like to do that.
Maybe we could add a link to these guidelines in issue template?

**Comment by pniedzwiedzinski** [comment]
Do you want the code of conduct to be included?

**Comment by quanghung97** [comment]
> Do you want the code of conduct to be included?

yeah, Of course. I would like CONTRIBUTE.md template for this repo

**Comment by pniedzwiedzinski** [comment]
I was thinking that it would be the most common: https://www.contributor-covenant.org/
